### ISSUE TITLE
공통 컴포넌트 Header, Footer 컴포넌트 UI 개발

### ISSUE THREAD

**Issue by Cho-SeongJu** [FootStepteam/footstep_FE#5]
공통 Component UI 개발
1. Header
2. Footer

기간: 06/04 ~ 06/05

**Comment by Cho-SeongJu** [comment]
Header, Footer 컴포넌트 작성완료하여 커밋 완료

기능 개발은 BE과 API 통신 테스트 이후 진행 예정

**Comment by pigjjun** [comment]
- 헤더 UI 개선
---6/30
