### ISSUE TITLE
채팅 UI 및 기능 개발

### ISSUE THREAD

**Issue by Cho-SeongJu** [FootStepteam/footstep_FE#55]
채팅방 기능 개발 예정

- socket.io 사용하여 BE와 같이 개발 진행 예정
- 채팅방 UI 개발 예정

**Comment by Cho-SeongJu** [comment]
채팅 UI 구현 완료 (06/26)

**Comment by pigjjun** [comment]
- socketJS 이용한 기초 코드 구현
- 추후 백엔드쪽 채팅 관련 코드 구현시 다시 확인 예정
예상 일정: 6/28

**Comment by pigjjun** [comment]
- 채팅 기능 구현 확인
- 채팅방 각 공유방의 채팅방으로 연결 구현 예정(6/30)
- UI 개선 필요

**Comment by pigjjun** [comment]
- UI개선 및 기능 구현 완료
---7/1
- UI 추가 개선
- 웹소켓 주소 변경
---7/4
