### ISSUE TITLE
사용자 프로필 페이지 컴포넌트 개발

### ISSUE THREAD

**Issue by Cho-SeongJu** [FootStepteam/footstep_FE#7]
로그인한 사용자 프로필 페이지 컴포넌트 개발

기능 개발은 BE과 API 통신 이후 개발 예정

기간 : 06/05~06/06

**Comment by pigjjun** [comment]
- 로그인 유저 정보 API 호출 및 표시
- 참여 중인 공유 일정 표시
-> planShareRoomEntrance, newPost 쪽 참여중인 공유 일정 가져오는 함수 커스텀 훅으로 관리
---(6/20)
- 상세 UI 추후 개발 예정

**Comment by pigjjun** [comment]
- Private 게시글은 본인 프로필에 뜨도록 구현 예정
